import { Product } from './product';

export const PRODUCTS: Product[] = [
{
  id: 0,
  artnr: '030200798',
  imageOne: '/assets/bilder/030200798.jpg',
  imageTwo: '/assets/bilder/51_3_3.jpg',
  title: '18k Gold plated filippa hoops',
  subText: 'Gör ett starkt modestatement med Filippa hoops av 18k guldpläterat silver. Dessa snyggingar är inte bara stora och chunky, utan har också en rustik och unik design som kommer att få allas huvuden att vändas efter dig när du passerar.',
  unit: 'Par',
  material: '18k Guldpläterat silver',
  color: 'Guld',
  size: '20mm',
  price: 749
},
{
  id: 1,
  artnr: '030100780',
  imageOne: '/assets/bilder/030100780.jpg',
  imageTwo: '/assets/bilder/58_1_2.jpg',
  title: 'Sterling silver baby chunky hoops',
  subText: 'Med Baby Chunky hoops i öronen så kan inget gå fel. Och luras inte av deras storlek, för dessa snyggingar är fullproppade av tidlös charm och elegans som kommer att ta alla dina outfits till en helt ny nivå.',
  unit: 'Par',
  material: '925 sterling silverr',
  color: 'Silver',
  size: '16mm',
  price: 449
},
{
  id: 2,
  artnr: '030200581',
  imageOne: '/assets/bilder/123175-925fg.jpg',
  imageTwo: '/assets/bilder/802d4f_2.jpg',
  title: '24K Gold plated mid chain hoops',
  subText: 'Mid Chain hoops av 24k guldpläterat silver gör det otroligt enkelt att få till en elegant och lyxig look. De kommer i en ljuvlig kedjedesign och kommer ta din outfit till en helt ny nivå.',
  unit: 'Par',
  material: '24k Guldpläterat silver',
  color: 'Guld',
  size: '18mm',
  price: 399
},
{
  id: 3,
  artnr: '030100760',
  imageOne: '/assets/bilder/123340-925-new.jpg',
  imageTwo: '/assets/bilder/pim_g_s_20_1.jpg',
  title: 'Sterling Silver Pim 30mm Hoops',
  subText: 'Om du är ute efter ett nytt par favorithoops har du hittat helt rätt! Säg hej till Pim 30 mm Hoops av sterling silver, ett par ursnygga örhängen med diamantskuren finish. Dessa hoops kommer att ge din look den perfekta balansen mellan vågat modelejon och chic fashionista.',
  unit: 'Par',
  material: '925 sterling silver',
  color: 'silver',
  size: '30mm',
  price: 399
},
{
  id: 4,
  artnr: '030100826',
  imageOne: '/assets/bilder/030100826.jpg',
  imageTwo: '/assets/bilder/030100826_1_.jpg',
  title: 'Sterling Silver Tiny Hoops',
  subText: 'Låt dig inte luras av namnet, för Tiny hoops av sterling silver kommer att smycka dig med en stor dos av skönhet och charm. Med en iögonfallande antik finish och en förtrollande design som kommer att få allas blickar att riktas mot dig kommer detta par garanterat att bli nya favoriter i samlingen.',
  unit: 'Par',
  material: '925 Sterling Silver',
  color: 'silver',
  size: '20mm',
  price: 449
},
{
  id: 5,
  artnr: '030200580',
  imageOne: '/assets/bilder/123177-925fg.jpg',
  imageTwo: '/assets/bilder/img_0371_1.jpg',
  title: '24k Gold Plated Big Chain Hoops',
  subText: 'Big Chain hoops av 24k guldpläterat silver är helt klart något utöver det vanliga. Dessa skönheter har nämligen en iögonfallande kedjedesign som kommer att få allas blickar att riktas mot dig. Perfekt för en queen som du!',
  unit: 'Par',
  material: '24k Guldpläterat silver',
  color: 'Guld',
  size: '19mm',
  price: 449
},
{
  id: 6,
  artnr: '030100639',
  imageOne: '/assets/bilder/123219-925.jpg',
  imageTwo: '/assets/bilder/2-00_1.jpg',
  title: 'Sterling Silver Coachella Hoops',
  subText: 'Varför nöja dig med något lagom när du kan smycka dig och stå ut ur mängden med de underbara hoopsen Coachella av sterling silver i öronen? Dessa snygga huggie hoops glittrar och glimmar och är det perfekta smycket för en rolig kväll med vännerna.',
  unit: 'Par',
  material: '925 sterling silver',
  color: 'Silver',
  size: '35mm',
  price: 449
},
{
  id: 7,
  artnr: '030200625',
  imageOne: '/assets/bilder/925fg.jpg',
  imageTwo: '',
  title: 'Ellinor Löfgren 24k Gold Plated',
  subText: 'Spela modekorten rätt genom att bära de bländande Ellinor Löfgren 24k Gold Plated Croissant Earrings. Dessa läckra glitter tings kommer att sätta stilstandarden vart du än går.',
  unit: 'Par',
  material: '24k Guldpläterat silver',
  color: 'Guld',
  size: '22mm',
  price: 899
},
{
  id: 8,
  artnr: '030200698',
  imageOne: '/assets/bilder/123278-925fg.jpg',
  imageTwo: '',
  title: '18k Gold Plated Womanhood Hoops',
  subText: 'Framhäv din kvinnlighet med dessa hoops av 18k guldpläterat silver med det passande namnet Womanhood. Dessa drömmiga glittriga skönheter kommer med ett hänge format som ett mynt med en ingraverad kvinnokropp och är det perfekta smycket för att hylla den starka kvinnan.',
  unit: 'Par',
  material: '18k Guldpläterat silver',
  color: 'Guld',
  size: '18mm',
  price: 399
},
{
  id: 9,
  artnr: '030100466',
  imageOne: '/assets/bilder/123093-925.jpg',
  imageTwo: '',
  title: 'Sterling Silver Faye 20mm Hoops',
  subText: 'Få till en snygg vardagsstil med de drömmiga och extra små hoopsen Faye 20 mm i sterling silver. Det sägs ju att less is more, och visst är det något speciellt med att sätta i ett enkelt, stilrent och glänsande par iögonfallande hoops i öronen?',
  unit: 'Par',
  material: '925 sterling silver',
  color: 'Silver',
  size: '20mm',
  price: 349
},
]
